from Pessoa import Pessoa

a=Pessoa()
a.Nome= input('qual o nome da pessoa: ')
a.Data_Nascimento= input('qual a data de nascimento da pesso: ')
a.Estado_civil= input('qual o nome da pessoa: ')
a.Sexo= input('qual o Sexo da pessoa: ')
a.Endereco= input('qual o Enderço da pessoa: ')
b=Pessoa()
b.Nome= input('qual o nome da pessoa: ')
b.Data_Nascimento= input('qual a data de nascimento da pesso: ')
b.Estado_civil= input('qual o nome da pessoa: ')
b.Sexo= input('qual o Sexo da pessoa: ')
b.Endereco= input('qual o Enderço da pessoa: ')
c=Pessoa()
c.Nome= input('qual o nome da pessoa: ')
c.Data_Nascimento= input('qual a data de nascimento da pesso: ')
c.Estado_civil= input('qual o nome da pessoa: ')
c.Sexo= input('qual o Sexo da pessoa: ')
c.Endereco= input('qual o Enderço da pessoa: ')
d=Pessoa()
d.Nome= input('qual o nome da pessoa: ')
d.Data_Nascimento= input('qual a data de nascimento da pesso: ')
d.Estado_civil= input('qual o nome da pessoa: ')
d.Sexo= input('qual o Sexo da pessoa: ')
d.Endereco= input('qual o Enderço da pessoa: ')
e=Pessoa()
e.Nome= input('qual o nome da pessoa: ')
e.Data_Nascimento= input('qual a data de nascimento da pesso: ')
e.Estado_civil= input('qual o nome da pessoa: ')
e.Sexo= input('qual o Sexo da pessoa: ')
e.Endereco= input('qual o Enderço da pessoa: ')

print(a.Nome+a.Data_Nascimento+a.Sexo+a.Endereco+a.Estado_civil)
print(b.Nome+b.Data_Nascimento+b.Sexo+b.Endereco+b.Estado_civil)
print(c.Nome+c.Data_Nascimento+c.Sexo+c.Endereco+c.Estado_civil)
print(d.Nome+d.Data_Nascimento+d.Sexo+d.Endereco+d.Estado_civil)
print(e.Nome+e.Data_Nascimento+e.Sexo+e.Endereco+e.Estado_civil)